//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncfusionWpfApp1.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncfusionWpfApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to AutoComplete.
        /// </summary>
        public static string ShellAutoCompletePage {
            get {
                return ResourceManager.GetString("ShellAutoCompletePage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to BusyIndicator.
        /// </summary>
        public static string ShellBusyIndicatorPage {
            get {
                return ResourceManager.GetString("ShellBusyIndicatorPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string ShellCarouselPage {
            get {
                return ResourceManager.GetString("ShellCarouselPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string ShellChartsPage {
            get {
                return ResourceManager.GetString("ShellChartsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DateTimeRangeNavigator.
        /// </summary>
        public static string ShellDateTimeRangeNavigatorPage {
            get {
                return ResourceManager.GetString("ShellDateTimeRangeNavigatorPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Diagrams.
        /// </summary>
        public static string ShellDiagramsPage {
            get {
                return ResourceManager.GetString("ShellDiagramsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DockingManager.
        /// </summary>
        public static string ShellDockingManagerPage {
            get {
                return ResourceManager.GetString("ShellDockingManagerPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DocumentContainer.
        /// </summary>
        public static string ShellDocumentContainerPage {
            get {
                return ResourceManager.GetString("ShellDocumentContainerPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to EditorControl.
        /// </summary>
        public static string ShellEditorControlPage {
            get {
                return ResourceManager.GetString("ShellEditorControlPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to GridControl.
        /// </summary>
        public static string ShellGridControlPage {
            get {
                return ResourceManager.GetString("ShellGridControlPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HeatMap.
        /// </summary>
        public static string ShellHeatMapPage {
            get {
                return ResourceManager.GetString("ShellHeatMapPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Kanban.
        /// </summary>
        public static string ShellKanbanPage {
            get {
                return ResourceManager.GetString("ShellKanbanPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to MenuAdv.
        /// </summary>
        public static string ShellMenuAdvPage {
            get {
                return ResourceManager.GetString("ShellMenuAdvPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to NavigationDrawer.
        /// </summary>
        public static string ShellNavigationDrawerPage {
            get {
                return ResourceManager.GetString("ShellNavigationDrawerPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to PdfViewer.
        /// </summary>
        public static string ShellPdfViewerPage {
            get {
                return ResourceManager.GetString("ShellPdfViewerPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to PivotGrid.
        /// </summary>
        public static string ShellPivotGridPage {
            get {
                return ResourceManager.GetString("ShellPivotGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to PropertyGrid.
        /// </summary>
        public static string ShellPropertyGridPage {
            get {
                return ResourceManager.GetString("ShellPropertyGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to RadialMenu.
        /// </summary>
        public static string ShellRadialMenuPage {
            get {
                return ResourceManager.GetString("ShellRadialMenuPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to RangeSlider.
        /// </summary>
        public static string ShellRangeSliderPage {
            get {
                return ResourceManager.GetString("ShellRangeSliderPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string ShellRatingPage {
            get {
                return ResourceManager.GetString("ShellRatingPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Ribbon.
        /// </summary>
        public static string ShellRibbonPage {
            get {
                return ResourceManager.GetString("ShellRibbonPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to RichTextBoxAdv.
        /// </summary>
        public static string ShellRichTextBoxAdvPage {
            get {
                return ResourceManager.GetString("ShellRichTextBoxAdvPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string ShellSchedulerPage {
            get {
                return ResourceManager.GetString("ShellSchedulerPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
           
    
            
    		 public static string SettingsPageRadioButtonMaterialDarkBlueTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkBlueTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialDark.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialLightBlue.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialLightBlueTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightBlueTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to MaterialLight.
            /// </summary>
            public static string SettingsPageRadioButtonMaterialLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019Black.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019BlackTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019BlackTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019Colorful.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019ColorfulTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019ColorfulTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019DarkGray.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019DarkGrayTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019DarkGrayTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019HighContrast.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019HighContrastTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019HighContrastTheme", resourceCulture);
                }
            }
            
            /// <summary>
            ///   Looks up a localized string similar to Office2019White.
            /// </summary>
            public static string SettingsPageRadioButtonOffice2019WhiteTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonOffice2019WhiteTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet.
        /// </summary>
        public static string ShellSpreadsheetPage {
            get {
                return ResourceManager.GetString("ShellSpreadsheetPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TabControlExt.
        /// </summary>
        public static string ShellTabControlExtPage {
            get {
                return ResourceManager.GetString("ShellTabControlExtPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TileView.
        /// </summary>
        public static string ShellTileViewPage {
            get {
                return ResourceManager.GetString("ShellTileViewPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ToolBarAdv.
        /// </summary>
        public static string ShellToolBarAdvPage {
            get {
                return ResourceManager.GetString("ShellToolBarAdvPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TreeGrid.
        /// </summary>
        public static string ShellTreeGridPage {
            get {
                return ResourceManager.GetString("ShellTreeGridPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TreeView.
        /// </summary>
        public static string ShellTreeViewPage {
            get {
                return ResourceManager.GetString("ShellTreeViewPage", resourceCulture);
            }
        }
    }
}
